// flow-typed signature: 604b3f223d69d9627db830d989871d80
// flow-typed version: <<STUB>>/wait-on_v^6.0.1/flow_v0.171.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wait-on'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "wait-on" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "wait-on/exampleConfig" {
  declare module.exports: any;
}

declare module "wait-on/lib/wait-on" {
  declare module.exports: any;
}

// Filename aliases
declare module "wait-on/exampleConfig.js" {
  declare module.exports: $Exports<"wait-on/exampleConfig">;
}
declare module "wait-on/lib/wait-on.js" {
  declare module.exports: $Exports<"wait-on/lib/wait-on">;
}
